# Generated by Django 3.2 on 2023-02-01 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='الإسم :')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='نبذة عنك :')),
                ('adress', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة:')),
                ('adress_detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان بالتفصيل:')),
                ('number_phone', models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف :')),
                ('working_hours', models.IntegerField(blank=True, null=True, verbose_name=' ساعات العمل :')),
                ('wating_time', models.IntegerField(blank=True, null=True, verbose_name=' مدة الإنتظار :')),
                ('spcalist_doctor', models.CharField(blank=True, max_length=500, null=True, verbose_name='متخصص في ؟ :')),
                ('join_new', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Male', 'Male'), ('Femal', 'Femal')], max_length=50, null=True, verbose_name='النوع: ')),
                ('who_i', models.TextField(blank=True, max_length=500, null=True, verbose_name=' من أنا : ')),
                ('doctor', models.CharField(blank=True, choices=[('عظام', 'عظام'), ('جلديه', 'جلديه'), ('أسنان', 'أسنان')], max_length=50, null=True, verbose_name=' دكتور؟:')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='السعر: ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name=' صورة لك:  ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook')),
                ('twiter', models.CharField(blank=True, max_length=50, null=True, verbose_name='twiter')),
                ('google', models.CharField(blank=True, max_length=50, null=True, verbose_name='google')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
