# Generated by Django 3.2 on 2023-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230126_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(default=1, max_length=50, verbose_name='المحافظة:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_detail',
            field=models.CharField(default=1, max_length=50, verbose_name='العنوان بالتفصيل:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' دكتور؟:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(default=1, verbose_name='رقم الهاتف :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='spcalist_doctor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='متخصص في ؟ :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=50, verbose_name='نبذة عنك :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twiter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wating_time',
            field=models.IntegerField(blank=True, null=True, verbose_name=' مدة الإنتظار :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name=' ساعات العمل :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80, verbose_name='الإسم :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=500, verbose_name=' من أنا : '),
        ),
    ]
