# Generated by Django 3.2 on 2023-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230127_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_us',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='وقت الإنضمام: '),
            preserve_default=False,
        ),
    ]
