# Generated by Django 3.2 on 2023-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(verbose_name='وقت الإنضمام: '),
        ),
    ]
