# Generated by Django 3.2 on 2023-01-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_join_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Male', 'Male'), ('Femal', 'Femal')], default=1, max_length=50, verbose_name='النوع: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الإنضمام: '),
        ),
    ]
