# Generated by Django 3.2 on 2023-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_join_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='وقت الإنضمام: '),
        ),
    ]
