# Generated by Django 3.2 on 2023-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_join_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adress_detail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='join_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spcalist_doctor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wating_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twiter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=500, verbose_name='نبذة عنك:  '),
        ),
    ]
